### ISSUE TITLE
StorageBootup should check status using nodetool only, rather than using nodetool and PID

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#4674]
1. `grakn server start` checks whether storage is ready using `nodetool`: https://github.com/graknlabs/grakn/blob/master/daemon/executor/Storage.java#L231
2. `grakn server status` checks whether storage is running using `ps -p <pid>`: https://github.com/graknlabs/grakn/blob/master/daemon/executor/Storage.java#L181

Ideally both #1 and #2 should be done using `nodetool`

**Comment by marco-scoppetta** [comment]
Checking if storage is running using `nodetool` when the user issues `grakn server status` will not give the guarantee that the running cassandra is a Grakn cassandra, whereas using the PID stored in our custom temp file allows us to check if the PID belong to a Grakn process:
https://github.com/graknlabs/grakn/blob/master/daemon/executor/Executor.java#L200
see that we check both if the process is running and if it is a Grakn process in `isAGraknProcess`.

We cannot only use the PID when user issues `grakn server start` because Cassandra takes some time before being in "ready" status, that's why we rely on `nodetool` for that

**Comment by flyingsilverfin** [comment]
N/A since we no lnoger use cassandra woooo
