### ISSUE TITLE
Get the label of an concept type with just one function call

### ISSUE THREAD

**Issue by kristall** [vaticle/typedb#5096]
## Problem to Solve

Getting the label now takes 2 calls `element.type().label()`, while getting the value just needs one `element.value()` (for example in an `for element in Entity.attributes()` loop). 

## Proposed Solution

Imho it be better if just one call was needed for example `element.label()` (as suggest by @sorsaffari).

I hope this request is clear enough, else just ask ...

**Comment by marco-scoppetta** [comment]
@kristall thanks for requesting this. We will maybe discuss this feature request internally, but just to make some clarity:

> while getting the value just needs one element.value()
This is because the value belongs to the element

> Getting the label now takes 2 calls element.type().label()
This is because the label belongs to the the type, not to the element itself, `element.label()` is logically wrong, maybe we can discuss adding a shortcut such as `element.typeLabel()`

**Comment by flyingsilverfin** [comment]
Closing as we currently are happy with the way of going from instance to type with `concept.type()`, and type to label with `.label()`

Note that concept instances always have their own type always embedded, so getting the `type()` doesn't cost a network round trip
