### ISSUE TITLE
Loading schema file causes locks

### ISSUE THREAD

**Issue by yogeshkodei** [vaticle/typedb#6282]
## Description

Files that were created for 1.8 and eventually modified for Grakn 2 do not load and causes locks

## Environment

1. OS (where Grakn server runs): {Mac OS 10}
2. Grakn version (and platform): { Grakn Core 2.0.0 }
3. Grakn client: { console }
4. Other environment details:

## Reproducible Steps

Will provide the schema files in a private message

## Expected Output
Load schema without issues of course
## Actual Output

Will provide log files in a private message
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by haikalpribadi** [comment]
Can you provide more information on what you mean by "do not load", @yogeshkodei ? What's the error message?

Opening a "schema session" indeed locks the database from opening other data transactions. When you close that schema session, the lock will be released. This is expected behaviour. 

We need more information on your issue so we can help you resolve it.

**Comment by yogeshkodei** [comment]
Daniel has the necessary files - schema files and the logs. I can send the server logs as well in a private message. 

I was trying to load my 1.84 files to Grakn 2. Change the syntax accordingly. Grakn Console does not complain after loading. However on the Grakn Server I can see a bunch of errors. Then when I try to commit on Console I get the error “No connection to the server”.

**Comment by yogeshkodei** [comment]
I have tried to shut down the server and console and restart it. But it still complains that there is a lock. I had to restart my machine to get the lock released.

**Comment by dmitrii-ubskii** [comment]
Closing as stale.
